return {
 ["content"]={
  ["files"]={
   ["ls-r"]="",
  },
  ["metadata"]={
   ["directories"]=0,
   ["files"]=1,
   ["path"]="selfautoparent:texmf-fonts",
   ["remappings"]=1,
  },
  ["remap"]={
   ["ls-r"]="ls-R",
  },
 },
 ["date"]="2018-04-30",
 ["root"]="selfautoparent:texmf-fonts",
 ["time"]="23:13:23",
 ["type"]="files",
 ["uuid"]="51b87069-4e04-abfc-8fbc-a3e3547cc981",
 ["version"]="1.100",
}