return {
 ["content"]={
  ["files"]={
   ["ls-r"]="",
  },
  ["metadata"]={
   ["directories"]=0,
   ["files"]=1,
   ["path"]="selfautoparent:texmf-local",
   ["remappings"]=1,
  },
  ["remap"]={
   ["ls-r"]="ls-R",
  },
 },
 ["date"]="2018-04-29",
 ["root"]="selfautoparent:texmf-local",
 ["time"]="22:57:09",
 ["type"]="files",
 ["uuid"]="e5a2a9a7-4efe-9ae4-0023-1cdc6325e067",
 ["version"]="1.100",
}